#' @title Function \code{write_example_workflowHelper}
#' @description Write files to generate the example workflow: i.e., 
#' produce \code{code.R} and \code{Makefile.R}
#' @export
write_example_workflowHelper = function(){
  dir = system.file("example", package = "workflowHelper")
  for(file in list.files(dir)){
    path = system.file("example", file, package = "workflowHelper")
    if (!file.exists(path)) stop("File ", file, 
      " is missing from installed package workflowHelper.", call.=FALSE)
    contents = readLines(path)
    write(contents, file)
  }
}

#' @title Function \code{setup_example_workflow}
#' @description Set up and run the package example: i.e., generate
#' the \code{remake} file and Makefile and run \code{make}.
#' @export
setup_example_workflowHelper = function(){
  write_example_workflowHelper()
  source("workflow.R")
}

#' @title Function \code{run_example_workflowHelper}
#' @description Set up and run the package example: i.e., generate
#' the \code{remake} file and Makefile and run \code{make}.
#' @export
#' @param intern TRUE/FALSE Argument to system to output to console or not.
run_example_workflowHelper = function(intern = F){
  setup_example_workflowHelper()
  system("make -j 8 2>&1", intern = intern)
}

#' @title Function \code{clean_example_workflowHelper}
#' @description Clean up files generated by the package example.
#' @export
#' @param intern Argument to system, option to capture output.
clean_example_workflowHelper = function(intern = F){
  system("make clean 2>&1", intern = intern)
  unlink(c("code.R", "figure", "latex.Rnw", "markdown.Rmd", "remake.yml",  
    "Makefile", "workflow.R"), recursive = T)
}
